config/routes.rb
Rails.application.routes.draw do
  resources :stock_settings

  resources :photo_links

  resources :data_caches

  resources :settings

  root 'static_pages#home'

  get '/train/', to: 'train#station'
  get '/bus/', to: 'bus#station'
  get '/stock/', to: 'stock#quote'
  get '/rss/', to: 'rss#feed'
  get '/notices/', to: 'settings#listNotices'
  get '/clearcache/', to: 'data_caches#clearAll'
  get '/setMessage/', to: 'static_pages#setMessage'
  get '/setImage/', to: 'static_pages#setImg'
  get '/checkRefresh/', to: 'static_pages#checkRefresh'
  get '/forceRefresh/', to: 'static_pages#forceRefresh'
  get '/getImages/', to: 'photo_links#getImages'
  get '/getPhotoRefresh/', to: 'settings#getPhotoRefresh'
  get '/getContentRefreshTime/', to: 'settings#getContentRefreshTime'

end

app/models/stock_setting.rb
class StockSetting < ActiveRecord::Base
end

app/controllers/stock_settings_controller.rb
class StockSettingsController < ApplicationController
  before_action :set_stock_setting, only: [:show, :edit, :update, :destroy]

  # GET /stock_settings
  # GET /stock_settings.json
  def index
    @stock_settings = StockSetting.all
  end

  # GET /stock_settings/1
  # GET /stock_settings/1.json
  def show
  end

  # GET /stock_settings/new
  def new
    @stock_setting = StockSetting.new
  end

  # GET /stock_settings/1/edit
  def edit
  end

  # POST /stock_settings
  # POST /stock_settings.json
  def create
    @stock_setting = StockSetting.new(stock_setting_params)

    respond_to do |format|
      if @stock_setting.save
        format.html { redirect_to @stock_setting, notice: 'Stock setting was successfully created.' }
        format.json { render :show, status: :created, location: @stock_setting }
      else
        format.html { render :new }
        format.json { render json: @stock_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stock_settings/1
  # PATCH/PUT /stock_settings/1.json
  def update
    respond_to do |format|
      if @stock_setting.update(stock_setting_params)
        format.html { redirect_to @stock_setting, notice: 'Stock setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock_setting }
      else
        format.html { render :edit }
        format.json { render json: @stock_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_settings/1
  # DELETE /stock_settings/1.json
  def destroy
    @stock_setting.destroy
    respond_to do |format|
      format.html { redirect_to stock_settings_url, notice: 'Stock setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_setting
      @stock_setting = StockSetting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_setting_params
      params.require(:stock_setting).permit(:symbol)
    end
end

app/helpers/stock_settings_helper.rb
module StockSettingsHelper
end

app/views/stock_settings/_form.html.erb
<%= form_for(@stock_setting) do |f| %>
  <% if @stock_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock_setting.errors.count, "error") %> prohibited this stock_setting from being saved:</h2>

      <ul>
      <% @stock_setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stock_settings/edit.html.erb
<h1>Editing Stock Setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock_setting %> |
<%= link_to 'Back', stock_settings_path %>

app/views/stock_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stock Settings</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stock_settings.each do |stock_setting| %>
      <tr>
        <td><%= stock_setting.symbol %></td>
        <td><%= link_to 'Show', stock_setting %></td>
        <td><%= link_to 'Edit', edit_stock_setting_path(stock_setting) %></td>
        <td><%= button_to 'Destroy', stock_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock setting', new_stock_setting_path %>

app/views/stock_settings/new.html.erb
<h1>New Stock Setting</h1>

<%= render 'form' %>

<%= link_to 'Back', stock_settings_path %>

app/views/stock_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Symbol:</strong>
  <%= @stock_setting.symbol %>
</p>

<%= link_to 'Edit', edit_stock_setting_path(@stock_setting) %> |
<%= link_to 'Back', stock_settings_path %>