config/routes.rb
Rails.application.routes.draw do
  resources :stock_settings

  resources :photo_links

  resources :data_caches

  resources :settings

  root 'static_pages#home'

  get '/train/', to: 'train#station'
  get '/bus/', to: 'bus#station'
  get '/stock/', to: 'stock#quote'
  get '/rss/', to: 'rss#feed'
  get '/notices/', to: 'settings#listNotices'
  get '/clearcache/', to: 'data_caches#clearAll'
  get '/setMessage/', to: 'static_pages#setMessage'
  get '/setImage/', to: 'static_pages#setImg'
  get '/checkRefresh/', to: 'static_pages#checkRefresh'
  get '/forceRefresh/', to: 'static_pages#forceRefresh'
  get '/getImages/', to: 'photo_links#getImages'
  get '/getPhotoRefresh/', to: 'settings#getPhotoRefresh'
  get '/getContentRefreshTime/', to: 'settings#getContentRefreshTime'

end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        DataCache.delete_all
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def listNotices
    require "json"
    firstSetting = Setting.first
    notices = firstSetting.notices

    htmlresp = "<div id=\"rss\"><div align=\"center\" class=\"rssTitle\">This Weeks Site News</div>"
    # for notice in notices
    htmlresp = "#{htmlresp}<div>"
    notices.each_line do |notice|
      htmlresp = "#{htmlresp} <div class=\"noticeItem\">#{notice}</div>"
    end
    htmlresp = "#{htmlresp}</div></div>"

    render :json => htmlresp
  end

  def getPhotoRefresh
    require "json"
    firstSetting = Setting.first
    photoRefresh = firstSetting.photoRefresh
    render :json => photoRefresh || 10001
  end

  def getContentRefreshTime
    require "json"
    firstSetting = Setting.first
    refreshtime = firstSetting.refreshtime
    render :json => refreshtime || 60001
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:rssfeed, :stocksymbol, :weathercode, :trainstation, :busstopcode, :refreshtime, :notices, :marquee,:photoRefresh)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rssfeed %><br>
    <%= f.text_field :rssfeed %>
  </div>
  <!-- <div class="field">
    <%= f.label :stocksymbol %><br>
    <%= f.text_field :stocksymbol %>
  </div> -->
  <!-- <div class="field">
    <%= f.label :weathercode %><br>
    <%= f.text_field :weathercode %>
  </div> -->
  <!-- <div class="field">
    <%= f.label :trainstation %><br>
    <%= f.text_field :trainstation %>
  </div>
  <div class="field">
    <%= f.label :busstopcode %><br>
    <%= f.number_field :busstopcode %>
  </div> -->
  <div class="field">
    <%= f.label :refreshtime %><br>
    <%= f.number_field :refreshtime %>
  </div>
  <div class="field">
    <%= f.label :photoRefresh %><br>
    <%= f.number_field :photoRefresh %>
  </div>
  <div class="field">
    <%= f.label :notices %><br>
    <%= f.text_area :notices ,:cols => "70", :rows => "10" %>
  </div>
  <div class="field">
    <%= f.label :marquee %><br>
    <%= f.text_area :marquee ,:cols => "100", :rows => "1" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Settings</h1>

<table>
  <thead>
    <tr>
      <th>Rssfeed</th>
      <th>Stocksymbol</th>
      <th>Weathercode</th>
      <th>Trainstation</th>
      <th>Busstopcode</th>
      <th>Info/Photo switch time</th>
      <th>Photo switch time</th>
      
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.rssfeed %></td>
        <td><%= setting.stocksymbol %></td>
        <td><%= setting.weathercode %></td>
        <td><%= setting.trainstation %></td>
        <td><%= setting.busstopcode %></td>
        <td><%= setting.refreshtime %></td>
        <td><%= setting.photoRefresh %></td>
      </tr>
      <tr>
      <td><b>Notices:</b></td>
        <td colspan="5"><%= setting.notices %></td>
        </tr>
        <tr>
      <td><b>Marquee:</b></td>
        <td colspan="5"><%= setting.marquee %></td>
        </tr>
        <td><%= link_to 'Show', setting %>
        <%= link_to 'Edit', edit_setting_path(setting) %>
        <%= button_to 'Delete', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <tr>
      <td colspan="6"><hr></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>
<%= link_to "Home", root_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rssfeed:</strong>
  <%= @setting.rssfeed %>
</p>

<p>
  <strong>Stocksymbol:</strong>
  <%= @setting.stocksymbol %>
</p>

<p>
  <strong>Weathercode:</strong>
  <%= @setting.weathercode %>
</p>

<p>
  <strong>Trainstation:</strong>
  <%= @setting.trainstation %>
</p>

<p>
  <strong>Busstopcode:</strong>
  <%= @setting.busstopcode %>
</p>

<p>
  <strong>Refreshtime:</strong>
  <%= @setting.refreshtime %>
</p>

<p>
  <strong>Notices:</strong>
  <%= @setting.notices %>
</p>

<p>
  <strong>Marquee:</strong>
  <%= @setting.marquee %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>