config/routes.rb
Rails.application.routes.draw do
  resources :stock_settings

  resources :photo_links

  resources :data_caches

  resources :settings

  root 'static_pages#home'

  get '/train/', to: 'train#station'
  get '/bus/', to: 'bus#station'
  get '/stock/', to: 'stock#quote'
  get '/rss/', to: 'rss#feed'
  get '/notices/', to: 'settings#listNotices'
  get '/clearcache/', to: 'data_caches#clearAll'
  get '/setMessage/', to: 'static_pages#setMessage'
  get '/setImage/', to: 'static_pages#setImg'
  get '/checkRefresh/', to: 'static_pages#checkRefresh'
  get '/forceRefresh/', to: 'static_pages#forceRefresh'
  get '/getImages/', to: 'photo_links#getImages'
  get '/getPhotoRefresh/', to: 'settings#getPhotoRefresh'
  get '/getContentRefreshTime/', to: 'settings#getContentRefreshTime'

end

app/controllers/data_caches_controller.rb
class DataCachesController < ApplicationController
  before_action :set_data_cach, only: [:show, :edit, :update, :destroy]

  # GET /data_caches
  # GET /data_caches.json
  def index
    @data_caches = DataCache.all
  end

  # GET /data_caches/1
  # GET /data_caches/1.json
  def show
  end

  def clearAll
    DataCache.delete_all
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Data cache blown away.' }
    end
  end

  # GET /data_caches/new
  def new
    @data_cach = DataCache.new
  end

  # GET /data_caches/1/edit
  def edit
  end

  # POST /data_caches
  # POST /data_caches.json
  def create
    @data_cach = DataCache.new(data_cach_params)

    respond_to do |format|
      if @data_cach.save
        format.html { redirect_to @data_cach, notice: 'Data cache was successfully created.' }
        format.json { render :show, status: :created, location: @data_cach }
      else
        format.html { render :new }
        format.json { render json: @data_cach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_caches/1
  # PATCH/PUT /data_caches/1.json
  def update
    respond_to do |format|
      if @data_cach.update(data_cach_params)
        format.html { redirect_to @data_cach, notice: 'Data cache was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_cach }
      else
        format.html { render :edit }
        format.json { render json: @data_cach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_caches/1
  # DELETE /data_caches/1.json
  def destroy
    @data_cach.destroy
    respond_to do |format|
      format.html { redirect_to data_caches_url, notice: 'Data cache was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_cach
      @data_cach = DataCache.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_cach_params
      params.require(:data_cach).permit(:stock, :rss, :bus, :train)
    end
end

app/helpers/data_caches_helper.rb
module DataCachesHelper
end

app/views/data_caches/_form.html.erb
<%= form_for(@data_cach) do |f| %>
  <% if @data_cach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_cach.errors.count, "error") %> prohibited this data_cach from being saved:</h2>

      <ul>
      <% @data_cach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stock %><br>
    <%= f.text_field :stock %>
  </div>
  <div class="field">
    <%= f.label :rss %><br>
    <%= f.text_field :rss %>
  </div>
  <div class="field">
    <%= f.label :bus %><br>
    <%= f.text_field :bus %>
  </div>
  <div class="field">
    <%= f.label :train %><br>
    <%= f.text_field :train %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_caches/edit.html.erb
<h1>Editing Data Cach</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_cach %> |
<%= link_to 'Back', data_caches_path %>

app/views/data_caches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Data Caches</h1>

<table>
  <thead>
    <tr>
      <th>Stock</th>
      <th>Rss</th>
      <th>Bus</th>
      <th>Train</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_caches.each do |data_cach| %>
      <tr>
        <td><%= data_cach.stock %></td>
        <td><%= data_cach.rss %></td>
        <td><%= data_cach.bus %></td>
        <td><%= data_cach.train %></td>
        <td><%= link_to 'Show', data_cach %></td>
        <td><%= link_to 'Edit', edit_data_cach_path(data_cach) %></td>
        <td><%= link_to 'Destroy', data_cach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data cache', new_data_cach_path %>

app/views/data_caches/new.html.erb
<h1>New Data Cach</h1>

<%= render 'form' %>

<%= link_to 'Back', data_caches_path %>

app/views/data_caches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stock:</strong>
  <%= @data_cach.stock %>
</p>

<p>
  <strong>Rss:</strong>
  <%= @data_cach.rss %>
</p>

<p>
  <strong>Bus:</strong>
  <%= @data_cach.bus %>
</p>

<p>
  <strong>Train:</strong>
  <%= @data_cach.train %>
</p>

<%= link_to 'Edit', edit_data_cach_path(@data_cach) %> |
<%= link_to 'Back', data_caches_path %>