config/routes.rb
Rails.application.routes.draw do
  resources :stock_settings

  resources :photo_links

  resources :data_caches

  resources :settings

  root 'static_pages#home'

  get '/train/', to: 'train#station'
  get '/bus/', to: 'bus#station'
  get '/stock/', to: 'stock#quote'
  get '/rss/', to: 'rss#feed'
  get '/notices/', to: 'settings#listNotices'
  get '/clearcache/', to: 'data_caches#clearAll'
  get '/setMessage/', to: 'static_pages#setMessage'
  get '/setImage/', to: 'static_pages#setImg'
  get '/checkRefresh/', to: 'static_pages#checkRefresh'
  get '/forceRefresh/', to: 'static_pages#forceRefresh'
  get '/getImages/', to: 'photo_links#getImages'
  get '/getPhotoRefresh/', to: 'settings#getPhotoRefresh'
  get '/getContentRefreshTime/', to: 'settings#getContentRefreshTime'

end

app/models/photo_link.rb
class PhotoLink < ActiveRecord::Base
end

app/controllers/photo_links_controller.rb
class PhotoLinksController < ApplicationController
  before_action :set_photo_link, only: [:show, :edit, :update, :destroy]

  respond_to :html
  layout false

  # GET /photo_links
  # GET /photo_links.json
  def index
    @photo_links = PhotoLink.order("created_at DESC")
  end

  # GET /photo_links/1
  # GET /photo_links/1.json
  def show
  end

  # GET /photo_links/new
  def new
    @photo_link = PhotoLink.new
  end

  # GET /photo_links/1/edit
  def edit
  end

  # POST /photo_links
  # POST /photo_links.json
  def create
    @photo_link = PhotoLink.new(photo_link_params)

    respond_to do |format|
      if @photo_link.save
        format.html { redirect_to @photo_link, notice: 'Photo link was successfully created.' }
        format.json { render :show, status: :created, location: @photo_link }
      else
        format.html { render :new }
        format.json { render json: @photo_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photo_links/1
  # PATCH/PUT /photo_links/1.json
  def update
    respond_to do |format|
      if @photo_link.update(photo_link_params)
        format.html { redirect_to @photo_link, notice: 'Photo link was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo_link }
      else
        format.html { render :edit }
        format.json { render json: @photo_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_links/1
  # DELETE /photo_links/1.json
  def destroy
    @photo_link.destroy
    respond_to do |format|
      format.html { redirect_to photo_links_url, notice: 'Photo link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def getImages()
    htmlresp = ""
    begin
      # setting limit of 10 here for image rotation, dont want to floor JS on browser
        photos = PhotoLink.where(hidden: false).limit(10)
        photoList = photos.map do |p|
          { :id => p.id, :url => p.url }
        end

        htmlresp = photoList.to_json

    rescue Exception => e
      puts "Problem getting images"
      puts e.backtrace.join("\n")
    end
    render :text => htmlresp
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo_link
      @photo_link = PhotoLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_link_params
      params.require(:photo_link).permit(:url, :hidden)
    end
end

app/helpers/photo_links_helper.rb
module PhotoLinksHelper
end

app/views/photo_links/_form.html.erb
<%= form_for(@photo_link) do |f| %>
  <% if @photo_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo_link.errors.count, "error") %> prohibited this photo_link from being saved:</h2>

      <ul>
      <% @photo_link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :hidden %><br>
    <%= f.check_box :hidden %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photo_links/edit.html.erb
<h1>Editing Photo Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo_link %> |
<%= link_to 'Back', photo_links_path %>

app/views/photo_links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photo Links</h1>

<table>
  <thead>
    <tr>
    <th></th>
      <th>Url</th>
      <th>Hidden</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <%= link_to 'New Photo link', new_photo_link_path %>
  <br/>
    <% @photo_links.each do |photo_link| %>
      <tr>
        <td><img src="<%= photo_link.url %>" width="100"></td>
        <td><%= photo_link.url %></td>
        <td><%= photo_link.hidden %></td>
        <td><%= link_to 'Show', photo_link %></td>
        <td><%= link_to 'Edit', edit_photo_link_path(photo_link) %></td>
        <td><%= button_to 'Delete', photo_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/photo_links/new.html.erb
<h1>New Photo Link</h1>

<%= render 'form' %>

<%= link_to 'Back', photo_links_path %>

app/views/photo_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @photo_link.url %>
</p>

<p>
  <strong>Hidden:</strong>
  <%= @photo_link.hidden %>
</p>

<%= link_to 'Edit', edit_photo_link_path(@photo_link) %> |
<%= link_to 'Back', photo_links_path %>